version: '3.8'
services:
  postgres:
    image: postgres:12
    volumes:
      - ./db-data:/db-data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=root
      - POSTGRES_DB=petDb
      - PG_DATA=/db-data
    ports:
      - 5432:5432