// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using petAdoptionApi.Models.Start_Model;

#nullable disable

namespace petAdoptionApi.Migrations
{
    [DbContext(typeof(PetAdoptionContext))]
    [Migration("20220802022257_AddSeed")]
    partial class AddSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("petAdoptionApi.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "SRD",
                            Name = "Freddy"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Tigrado",
                            Name = "Jaja"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Frajola",
                            Name = "Murphy"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Laranja",
                            Name = "Hermione"
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Frajola",
                            Name = "Faraday"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
